/* eslint-disable */
// Generated by `convex dev`
// Do not manually edit.
// TEMPORARY MOCK - Replace with real convex generated code

// This is a temporary mock that allows the app to build
// Run `npx convex dev` to generate the real API

export const api = {
  tasks: {
    getAll: "tasks/getAll" as unknown as Function,
    getByStatus: "tasks/getByStatus" as unknown as Function,
    create: "tasks/create" as unknown as Function,
    update: "tasks/update" as unknown as Function,
    updateStatus: "tasks/updateStatus" as unknown as Function,
    remove: "tasks/remove" as unknown as Function,
  },
  memories: {
    getAll: "memories/getAll" as unknown as Function,
    search: "memories/search" as unknown as Function,
    getByCategory: "memories/getByCategory" as unknown as Function,
    getStats: "memories/getStats" as unknown as Function,
    create: "memories/create" as unknown as Function,
    update: "memories/update" as unknown as Function,
    remove: "memories/remove" as unknown as Function,
  },
};

export const internal = api;
