/* eslint-disable */
// Generated by `convex dev`
// Do not manually edit.

import type {
  ActionBuilder,
  HttpActionBuilder,
  MutationBuilder,
  QueryBuilder,
} from "convex/server";

export type QueryCtx = any;
export type MutationCtx = any;
export type ActionCtx = any;
export type HttpActionCtx = any;

export declare const query: QueryBuilder<any, any>;
export declare const mutation: MutationBuilder<any, any>;
export declare const action: ActionBuilder<any, any>;
export declare const httpAction: HttpActionBuilder<any, any>;
